package com.ecommerce.config;

import com.ecommerce.domain.Product;
import com.ecommerce.domain.ProductRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVParser;
import org.apache.commons.csv.CSVRecord;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.core.io.Resource;
import org.springframework.core.io.ResourceLoader;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.Reader;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;

/**
 * Loads the product catalog from a CSV file at startup.
 *
 * <p>Design notes:
 * <ul>
 *   <li>The CSV location is configurable via {@code app.catalog.csv-location}
 *       (a Spring Resource string; classpath or file).</li>
 *   <li>The CSV is seed data. Products are inserted only when their {@code productId}
 *       is absent. Once inserted, the database is the source of truth and existing
 *       products are never synchronized from the CSV.</li>
 *   <li>The CSV {@code id} column is intentionally ignored: {@code id} is the internal
 *       technical PK and is always generated by the database, never trusted from the CSV.</li>
 *   <li>Each row is validated against the domain invariants; invalid rows are logged
 *       and skipped (non-fatal) so one bad row cannot abort the whole import.</li>
 * </ul>
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class CatalogCsvLoader implements ApplicationRunner {

    // These MUST be final so Lombok's @RequiredArgsConstructor injects them.
    // The original code left the repository non-final, so it was never injected
    // and produced a NullPointerException on startup.
    private final ProductRepository productRepository;
    private final ResourceLoader resourceLoader;

    @Value("${app.catalog.csv-location:classpath:products_300.csv}")
    private String csvLocation;

    @Override
    @Transactional
    public void run(ApplicationArguments args) {
        Resource resource = resourceLoader.getResource(csvLocation);
        if (!resource.exists()) {
            log.error("[PRODUCT-SERVICE] Catalog CSV not found at '{}'. Skipping import.", csvLocation);
            return;
        }

        log.info("[PRODUCT-SERVICE] Importing catalog from '{}'...", csvLocation);
        int inserted = 0;
        int existing = 0;
        int skipped = 0;
        long rowNumber = 1; // header is row 1

        CSVFormat format = CSVFormat.DEFAULT.builder()
                .setHeader()
                .setSkipHeaderRecord(true)
                .setIgnoreHeaderCase(true)
                .setTrim(true)
                .build();

        try (Reader reader = new BufferedReader(
                new InputStreamReader(resource.getInputStream(), StandardCharsets.UTF_8));
             CSVParser parser = CSVParser.parse(reader, format)) {

            for (CSVRecord record : parser) {
                rowNumber++;
                try {
                    ParsedRow row = parseAndValidate(record);
                    boolean wasInserted = insertIfAbsent(row);
                    if (wasInserted) {
                        inserted++;
                    } else {
                        existing++;
                    }
                } catch (RowValidationException | IllegalArgumentException ex) {
                    skipped++;
                    log.warn("[PRODUCT-SERVICE] Skipping invalid CSV row {} | {}", rowNumber, ex.getMessage());
                }
            }
        } catch (Exception e) {
            log.error("[PRODUCT-SERVICE] Fatal error reading catalog CSV", e);
            return;
        }

        log.info("[PRODUCT-SERVICE] Catalog initialization finished | inserted={} | existing={} | skipped={}",
                inserted, existing, skipped);
    }

    /** Returns true only when the seed row produced a new persisted product. */
    private boolean insertIfAbsent(ParsedRow row) {
        if (productRepository.findByProductId(row.productId()).isPresent()) {
            return false;
        }

        Product product = Product.create(
                row.productId(),
                row.name(),
                row.price(),
                row.stock(),
                row.active()
        );
        productRepository.save(product);
        return true;
    }

    /**
     * Parse a CSV record and enforce the domain invariants.
     */
    private ParsedRow parseAndValidate(CSVRecord record) {
        String productId = record.isMapped("productId") ? record.get("productId") : null;
        String name = record.isMapped("name") ? record.get("name") : null;
        String rawPrice = record.isMapped("price") ? record.get("price") : null;
        String rawStock = record.isMapped("stock") ? record.get("stock") : null;
        String rawActive = record.isMapped("active") ? record.get("active") : "true";

        if (productId == null || productId.isBlank()) {
            throw new RowValidationException("productId is required");
        }
        if (name == null || name.length() < 3 || name.length() > 150) {
            throw new RowValidationException("name must be 3-150 chars (was '" + name + "')");
        }

        BigDecimal price;
        try {
            price = new BigDecimal(rawPrice);
        } catch (NumberFormatException e) {
            throw new RowValidationException("price is not a number (was '" + rawPrice + "')");
        }
        if (price.compareTo(BigDecimal.ZERO) <= 0) {
            throw new RowValidationException("price must be > 0 (was '" + rawPrice + "')");
        }

        int stock;
        try {
            stock = Integer.parseInt(rawStock);
        } catch (NumberFormatException e) {
            throw new RowValidationException("stock is not an integer (was '" + rawStock + "')");
        }
        if (stock < 0) {
            throw new RowValidationException("stock must be >= 0 (was '" + rawStock + "')");
        }

        if (!"true".equalsIgnoreCase(rawActive) && !"false".equalsIgnoreCase(rawActive)) {
            throw new RowValidationException("active must be true or false (was '" + rawActive + "')");
        }
        boolean active = "true".equalsIgnoreCase(rawActive);
        return new ParsedRow(productId, name, price, stock, active);
    }

    /** Immutable, already-validated view of a CSV row. */
    private record ParsedRow(String productId, String name, BigDecimal price, int stock, boolean active) {
    }

    /** Signals that a single row failed validation and must be skipped. */
    private static class RowValidationException extends RuntimeException {
        RowValidationException(String message) {
            super(message);
        }
    }
}
